version: '3.4'

services:
    frontend:
        container_name: cards_frontend
        build:
            context: "."
            target: dev # Build stage
            args:
                DDE_UID: ${DDE_UID} # Pass your UID (DDE_UID is set automatically)
                DDE_GID: ${DDE_GID} # Pass your GID (DDE_GID is set automatically)s
        volumes:
            - ./:/var/www
        environment:
            - VIRTUAL_HOST=cards.test
            - OPEN_URL=http://cards.test/

networks:
    default:
        name: "dde"
        external: true
